ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER GAMERANKING IDENTIFIED BY tecsis;

GRANT CREATE SESSION TO GAMERANKING;

ALTER USER GAMERANKING QUOTA UNLIMITED ON USERS;

CREATE TABLE JOGADORES
(
    IDJOGADOR   INTEGER,
    NOMEJOGADOR VARCHAR2(50),
    QTDPARTIDAS INTEGER DEFAULT 0,
    QTDVITORIAS INTEGER DEFAULT 0,

    CONSTRAINT PK_JOGADORES PRIMARY KEY (IDJOGADOR)
);

CREATE TABLE PARTIDAS
(
    IDPARTIDA     INTEGER,
    DTINIC        TIMESTAMP DEFAULT SYSDATE,
    DTFIM         TIMESTAMP,
    IDJOGADORVENC INTEGER,

    CONSTRAINT PK_PARTIDAS PRIMARY KEY (IDPARTIDA),
    CONSTRAINT FK_IDJOGADORVENC_PARTIDAS_JOGADORES FOREIGN KEY (IDJOGADORVENC) REFERENCES JOGADORES (IDJOGADOR)
);

CREATE TABLE JOGADORESPARTIDAS
(
    IDJOGADOR INTEGER,
    IDPARTIDA INTEGER,

    CONSTRAINT PK_JOGADORESPARTIDAS PRIMARY KEY (IDJOGADOR, IDPARTIDA),
    CONSTRAINT FK_JOGADORESPARTIDAS_PARTIDAS_IDPARTIDA FOREIGN KEY (IDPARTIDA) REFERENCES PARTIDAS (IDPARTIDA),
    CONSTRAINT FK_JOGADORESPARTIDAS_JOGADORES_IDJOGADOR FOREIGN KEY (IDJOGADOR) REFERENCES JOGADORES (IDJOGADOR)
);

CREATE SEQUENCE SQ_JOGADORES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_PARTIDAS
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SQ_JOGADORESPARTIDAS
    START WITH 1
    INCREMENT BY 1;
